global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "motorbike-rental-backend-v2"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:3005"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
